# Generated by Django 4.2.7 on 2024-02-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
