# Generated by Django 4.2.7 on 2024-03-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность учителя')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='group',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата конца подписки'),
        ),
        migrations.AddField(
            model_name='group',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата начала подписки'),
        ),
        migrations.AddField(
            model_name='group',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Учитель')], max_length=20, verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialty', verbose_name='Специальность'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
