# Generated by Django 5.0.1 on 2024-02-17 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='speciality',
        ),
        migrations.AddField(
            model_name='employee',
            name='teachers',
            field=models.ManyToManyField(to='core.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.position', verbose_name='Должность'),
        ),
    ]
