# Generated by Django 4.2.7 on 2024-02-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='Специальность учителя'),
        ),
    ]
