# Generated by Django 5.0.1 on 2024-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_specialty_remove_profile_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default=1, max_length=20, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
