# Generated by Django 4.2.7 on 2024-02-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
