# Generated by Django 5.0.3 on 2024-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_name_student_user_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Archived')], default=1, max_length=20, verbose_name='Статус'),
        ),
    ]
