# Generated by Django 5.0.1 on 2024-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.course', verbose_name='Курс обучения'),
        ),
    ]
