# Generated by Django 5.0.1 on 2024-02-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employee_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Specialty',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
    ]
