# Generated by Django 4.2.7 on 2024-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr',
        ),
        migrations.AddField(
            model_name='teacher',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qr',
            field=models.ImageField(null=True, upload_to='students_qr/'),
        ),
    ]
