# Generated by Django 4.2.7 on 2024-03-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_teacher_specialty_remove_group_teacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
