# Generated by Django 5.0.1 on 2024-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(1, 'Администратор'), (2, 'Учитель'), (3, 'Кассир')], default=1, verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
