# Generated by Django 5.0.1 on 2024-02-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_position_options_remove_employee_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
