# Generated by Django 5.0.1 on 2024-02-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_student_code_remove_student_qr_teacher_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='code',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qr',
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qr',
            field=models.ImageField(null=True, upload_to='students_qr/'),
        ),
    ]
