# Generated by Django 5.0.1 on 2024-03-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Администратор', 'Administrator'), ('Учитель', 'Teacher'), ('Кассир', 'Cashier')], default='Администратор', max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialty', verbose_name='Специальность'),
        ),
    ]
