# Generated by Django 5.0.1 on 2024-02-11 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_student_code_remove_student_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Учитель'),
            preserve_default=False,
        ),
    ]
