# Generated by Django 5.0.1 on 2024-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='speciality',
            field=models.CharField(max_length=100, verbose_name='Специальность'),
        ),
    ]
