# Generated by Django 5.0.1 on 2024-02-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
